#!/bin/bash

TACO_ENABLE_QUERY_DEBUG_LOG=true \
  TACO_DATABASE_HOST=localhost \
  TACO_DATABASE_PORT=25432 \
  TACO_DATABASE_DATABASE=taco \
  TACO_DATABASE_USERNAME=postgres \
  TACO_DATABASE_PASSWORD=postgres \
  TACO_DATABASE_SCHEMA=taco \
  TACO_SMS_SENDER_ENDPOINT="api.coolsms.co.kr" \
  TACO_SMS_SENDER_PHONE="01083047880" \
  TACO_SMS_SENDER_API_KEY=NCSCVKFUSA8TPSED \
  TACO_SMS_SENDER_API_SECRET=L25KAYEICPWCPHTIXMKLTEAKWLFFGIHQ \
  TACO_PAYMENT_SERVICE_ENDPOINT="https://api.tosspayments.com" \
  TACO_PAYMENT_SERVICE_API_SECRET="dGVzdF9za196WExrS0V5cE5BcldtbzUwblgzbG1lYXhZRzVSOg==" \
  TACO_ROUTE_SERVICE_ENDPOINT="https://naveropenapi.apigw.ntruss.com" \
  TACO_ROUTE_SERVICE_API_KEY="s9i06iew36" \
  TACO_ROUTE_SERVICE_API_SECRET="hvVaEKpxiu6XT9RqvEdH7JTF3uGJpDShdjZ6nIJi" \
  TACO_LOCATION_SERVICE_ENDPOINT="https://dapi.kakao.com" \
  TACO_LOCATION_SERVICE_API_SECRET="c46bd6c102717c6453ae7f0e6630a408" \
  TACO_BACKOFFICE_SECRET="backoffice_secret" \
  GOOGLE_APPLICATION_CREDENTIALS=/Users/kimtkyeom/.firebase/service_account.json \
  TACO_NOTIFICATION_TOPIC_URI="https://sqs.ap-northeast-2.amazonaws.com/069049357473/test-sqs" \
  TACO_TAXICALL_TOPIC_URI="https://sqs.ap-northeast-2.amazonaws.com/069049357473/test-sqs-taxicall" \
  TACO_NOTIFICATION_OUTBOX_EVENT_URIS="TaxiCallNotification/User,TaxiCallNotification/Driver" \
  TACO_NOTIFICATION_OUTBOX_POLL_INTERVAL="200ms" \
  TACO_NOTIFICATION_OUTBOX_MAX_MESSAGES=50 \
  TACO_TAXICALL_OUTBOX_EVENT_URIS="TaxiCall/Process" \
  TACO_TAXICALL_OUTBOX_POLL_INTERVAL="200ms" \
  TACO_TAXICALL_OUTBOX_MAX_MESSAGES=50 \
  TACO_TAXICALL_APP_WORKER_POOL_SIZE=10 \
  TACO_IMAGE_URL_SERVICE_TIMEOUT="168h" \
  TACO_IMAGE_URL_SERVICE_BUCKET="tacolabs-testbucket" \
  TACO_IMAGE_URL_SERVICE_BASE_PATH="dev/drivers" \
  TACO_IMAGE_URL_SERVICE_MAX_CACHE_SIZE_BYTES="10000" \
  TACO_IMAGE_URL_SERVICE_MAX_CACHE_SIZE_ENTRIES="1000" \
  go run go/cmd/server/main.go
