#!/bin/bash

TACO_ENABLE_QUERY_DEBUG_LOG=true \
  TACO_DATABASE_HOST=localhost \
  TACO_DATABASE_PORT=25432 \
  TACO_DATABASE_DATABASE=taco \
  TACO_DATABASE_USERNAME=postgres \
  TACO_DATABASE_PASSWORD=postgres \
  TACO_DATABASE_SCHEMA=taco \
  TACO_SMS_SENDER_ENDPOINT="api.coolsms.co.kr" \
  TACO_SMS_SENDER_PHONE="01083047880" \
  TACO_SMS_SENDER_API_KEY=NCSCVKFUSA8TPSED \
  TACO_SMS_SENDER_API_SECRET=L25KAYEICPWCPHTIXMKLTEAKWLFFGIHQ \
  TACO_PAYMENT_SERVICE_ENDPOINT="https://api.tosspayments.com" \
  TACO_PAYMENT_SERVICE_API_SECRET="dGVzdF9za196WExrS0V5cE5BcldtbzUwblgzbG1lYXhZRzVSOg==" \
  TACO_ROUTE_SERVICE_ENDPOINT="https://naveropenapi.apigw.ntruss.com" \
  TACO_ROUTE_SERVICE_API_KEY="s9i06iew36" \
  TACO_ROUTE_SERVICE_API_SECRET="hvVaEKpxiu6XT9RqvEdH7JTF3uGJpDShdjZ6nIJi" \
  TACO_LOCATION_SERVICE_ENDPOINT="https://dapi.kakao.com" \
  TACO_LOCATION_SERVICE_API_SECRET="c46bd6c102717c6453ae7f0e6630a408" \
  TACO_BACKOFFICE_SECRET="backoffice_secret" \
  go run go/cmd/main.go
