#!/bin/bash
set -e

export PGPASSWORD="$POSTGRES_PASSWORD"

psql -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER" << EOF
CREATE DATABASE "$POSTGRES_DATABASE";
EOF

psql -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d "$POSTGRES_DATABASE" << EOF
CREATE EXTENSION IF NOT EXISTS postgis;
EOF
