FROM taco:dev as builder
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-w -s' -o main ./go/cmd/outbox/main.go

FROM gcr.io/distroless/static-debian11

WORKDIR /

COPY --from=builder /go/src/github.com/taco-labs/taco/main /main
COPY --from=builder /go/src/github.com/taco-labs/taco/go/templates /go/templates

CMD ["/main"]
