FROM taco:dev as builder
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -ldflags '-w -s' -o main ./go/cmd/local/main.go

FROM golang:1.19.0-bullseye 

WORKDIR /

RUN apt update && apt install -y postgresql-client

COPY --from=builder /go/src/github.com/taco-labs/taco/main /main
COPY --from=builder /go/src/github.com/taco-labs/taco/go/templates /go/templates

COPY ./docker/entrypoint.server.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh", "/main"]
