FROM alpine:3.17.0 as builder

RUN apk add go gcc musl-dev
RUN go install ariga.io/atlas/cmd/atlas@v0.8.3

FROM alpine:3.17.0

RUN apk add --no-cache postgresql14-client  musl-dev

COPY --from=builder /root/go/bin/atlas /atlas
RUN install -o root -g root -m 0755 /atlas /usr/local/bin/atlas

COPY ./docker/entrypoint.migration.sh /entrypoint.sh

WORKDIR /schemas

COPY ./schemas/* ./

ENTRYPOINT [ "sh", "/entrypoint.sh" ]
