FROM golang:1.19.2-bullseye as builder

WORKDIR /go/src/github.com/taco-labs/taco
COPY ./go.mod ./go.sum ./
COPY ./go-cloud/go.mod ./go-cloud/go.sum ./go-cloud/

RUN go mod download

COPY ./go ./go
COPY ./go-cloud ./go-cloud
