FROM taco:dev as builder

FROM golang:1.19.0-bullseye 
RUN apt update && apt install -y postgresql-client
COPY --from=builder /go/src/github.com/ktk1012/taco/main /main

COPY ./docker/entrypoint.server.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh", "/main"]
