FROM ubuntu:20.04 

RUN apt update && apt install -y postgresql-client curl

RUN curl -LO https://release.ariga.io/atlas/atlas-linux-amd64-latest
RUN install -o root -g root -m 0755 ./atlas-linux-amd64-latest /usr/local/bin/atlas

COPY ./docker/entrypoint.migration.sh /entrypoint.sh

WORKDIR /schemas

COPY ./schemas/* ./

ENTRYPOINT [ "/entrypoint.sh" ]
