FROM taco:dev as builder

FROM gcr.io/distroless/static-debian11

COPY --from=builder /go/src/github.com/ktk1012/taco/main /main

COPY ./docker/entrypoint.server.sh /entrypoint.sh

ENTRYPOINT ["/main"]
